services:
  - docker

install: true

before_script:
  - docker login -u=jat001 -p="$DOCKER_PASSWD"

script:
  - docker build -t jat001/idea:$TRAVIS_TAG --build-arg VER=$TRAVIS_TAG .
  - docker tag jat001/idea:$TRAVIS_TAG jat001/idea:latest

  - docker push jat001/idea:$TRAVIS_TAG
  - docker push jat001/idea:latest
